version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

# services:
#   spring-app:
#     image: hello-spring
#     ports:
#       - "8082:8082"
